### ISSUE TITLE
Problem at running docker containers

### ISSUE THREAD

**Issue by gabrielkrneiro** [GabrielCarneiroDeveloper/flask-blueprint-factory-app#5]
# Instructions
- Build image
```
make build
```

- to get stack running
```
docker run -p 8080:5010 --name flask_auth flask_auth_gabrielcarneirodeveloper:latest
```

# issue
Despite setup.py dependencies to be installed in docker build process, the follow output keeps to be returned
```
gunicorn: Command not found
```

Although, if you enter in a container created based on built image and try to run `gunicorn --version` the command is found.

**Comment by GabrielCarneiroDeveloper** [comment]
- Build image
```
make build
```

- to get stack running
```
docker run -p 8080:5010 --name flask_auth flask_auth_gabrielcarneirodeveloper:latest
```

issue:
Despite setup.py dependencies to be installed in docker build process, the follow output keeps to be returned
```
gunicorn: Command not found
```

Although, if you enter in a container created based on built image and try to run `gunicorn --version` the command is found.

**Comment by gabrielkrneiro** [comment]
It have been solved mainly changing the base image and the way the project is copied into building docker image.

[Commit 87d9e11](https://github.com/GabrielCarneiroDeveloper/flask-blueprint-factory-app/commit/87d9e1199e4dec2c23216d61411208304629b0a2)
[Pull Request 6](https://github.com/GabrielCarneiroDeveloper/flask-blueprint-factory-app/pull/6)
